import { Language } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    loginTitle: "Welcome Back",
    signupTitle: "Create Account",
    phoneLabel: "Phone Number",
    passwordLabel: "Password",
    loginBtn: "Log In",
    signupBtn: "Sign Up",
    switchSignup: "Need an account? Sign Up",
    switchLogin: "Have an account? Log In",
    dashboard: "Dashboard",
    history: "History",
    logout: "Logout",
    cropAnalysis: "Crop Analysis",
    soilAnalysis: "Soil Analysis",
    cropDesc: "Detect diseases and get health advice for your crops.",
    soilDesc: "Analyze soil quality and get fertilizer recommendations.",
    takePhoto: "Take Photo",
    uploadPhoto: "Upload Image",
    analyzing: "Analyzing...",
    save: "Save Result",
    delete: "Delete",
    condition: "Condition",
    recommendations: "Recommendations",
    actions: "Next Actions",
    weather: "Current Weather",
    weatherError: "Weather unavailable",
    noHistory: "No analysis history found.",
    savedSuccess: "Result saved to history!",
    cameraError: "Could not access camera.",
    confirmDelete: "Are you sure you want to delete this?",
    selectImage: "Select or Capture an Image",
    analyzeBtn: "Analyze Image"
  },
  [Language.HINDI]: {
    loginTitle: "वापसी पर स्वागत है",
    signupTitle: "खाता बनाएं",
    phoneLabel: "फ़ोन नंबर",
    passwordLabel: "पासवर्ड",
    loginBtn: "लॉग इन करें",
    signupBtn: "साइन अप करें",
    switchSignup: "खाता नहीं है? साइन अप करें",
    switchLogin: "खाता है? लॉग इन करें",
    dashboard: "डैशबोर्ड",
    history: "इतिहास",
    logout: "लॉग आउट",
    cropAnalysis: "फसल विश्लेषण",
    soilAnalysis: "मिट्टी विश्लेषण",
    cropDesc: "अपनी फसलों के लिए बीमारियों का पता लगाएं और स्वास्थ्य सलाह लें।",
    soilDesc: "मिट्टी की गुणवत्ता का विश्लेषण करें और उर्वरक सुझाव प्राप्त करें।",
    takePhoto: "फोटो लें",
    uploadPhoto: "तस्वीर अपलोड करें",
    analyzing: "विश्लेषण कर रहा है...",
    save: "परिणाम सहेजें",
    delete: "हटाएं",
    condition: "स्थिति",
    recommendations: "सुझाव",
    actions: "अगले कदम",
    weather: "वर्तमान मौसम",
    weatherError: "मौसम अनुपलब्ध",
    noHistory: "कोई पिछला इतिहास नहीं मिला।",
    savedSuccess: "परिणाम इतिहास में सहेजा गया!",
    cameraError: "कैमरे तक नहीं पहुंच सका।",
    confirmDelete: "क्या आप वाकई इसे हटाना चाहते हैं?",
    selectImage: "एक छवि चुनें या लें",
    analyzeBtn: "छवि का विश्लेषण करें"
  }
};

export const WEATHER_CODES: Record<number, string> = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  71: "Slight snow",
  73: "Moderate snow",
  75: "Heavy snow",
  95: "Thunderstorm",
};